name: Validate Branch Name
description: >
  Enforces branch naming conventions. Fails if the PR source branch does not
  start with feature/, bugfix/, hotfix/, or release/.
  Only runs on pull_request events; skipped silently on push.

inputs:
  allowed-prefixes:
    description: >
      Comma-separated list of allowed branch prefixes (without the slash).
      Override only if your repo uses different conventions.
    required: false
    default: "feature,bugfix,hotfix,release"

runs:
  using: composite
  steps:
    - name: Validate Branch Name
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        BRANCH="${{ github.head_ref }}"
        echo "PR source branch: $BRANCH"

        # Build regex from allowed-prefixes input
        PREFIXES="${{ inputs.allowed-prefixes }}"
        REGEX="^($(echo "$PREFIXES" | tr ',' '|'))/"

        if [[ "$BRANCH" =~ $REGEX ]]; then
          echo "✅ Branch name '$BRANCH' follows naming convention"
        else
          echo "::error::Branch name '$BRANCH' does not follow the required naming convention."
          echo "::error::Allowed prefixes: $(echo "$PREFIXES" | tr ',' '/')/"
          echo "::error::Please rename your branch and re-open the PR."
          exit 1
        fi
